pytest_plugins = [
    "tests.fixtures.db",
    "tests.fixtures.client",
    "tests.fixtures.auth",
    "tests.fixtures.config",
    "tests.fixtures.core_mocks",
    "tests.integration.fixtures.user",
    "tests.integration.fixtures.project",
    "tests.integration.fixtures.document",
    "tests.integration.fixtures.project_member",
    "tests.unit.fixtures.repos",
    "tests.unit.fixtures.storage",
    "tests.unit.fixtures.domains",
    "tests.unit.fixtures.services",
    "tests.unit.fixtures.usages",
]
